// =============================================================================
// SUITE VET / FITBET 2.2 — modules/micro/data.js
// Base relacional del ecosistema microbiologico.
// =============================================================================

window.MICRO_DATA = {
  perfilesPlaca: [
    { id: "pequena", label: "Placa Petri pequeña", detalle: "~15 mL", volumenMl: 15 },
    { id: "estandar", label: "Placa Petri estándar", detalle: "~22 mL", volumenMl: 22 },
    { id: "alta", label: "Placa estándar alta", detalle: "~25 mL", volumenMl: 25 }
  ],

  agares: [
    {
      id: "bismuth-sulfite-agar",
      tipoEntidad: "agar",
      nombre: "Bismuth Sulphite Agar",
      alternativo: "Agar sulfito de bismuto / Wilson-Blair",
      subtitulo: "Para: Salmonella spp.",
      tipos: ["selectivo", "diferencial", "salmonella"],
      gramosPorLitro: 52.3,
      phFinal: "7.7 ± 0.2",
      objetivo: "Aislamiento selectivo de Salmonella, especialmente cepas productoras de H2S.",
      bacteriasObjetivoIds: ["salmonella-spp"],
      bacteriasInhibidas: ["Gram positivas", "flora acompañante intestinal", "coliformes sensibles"],
      composicion: [
        { ingrediente: "Peptona / polipeptona", cantidad: "10 g" },
        { ingrediente: "Extracto de carne", cantidad: "5 g" },
        { ingrediente: "Dextrosa", cantidad: "5 g" },
        { ingrediente: "Fosfato disódico", cantidad: "4 g" },
        { ingrediente: "Sulfato ferroso", cantidad: "0.3 g" },
        { ingrediente: "Sulfito de bismuto", cantidad: "8 g" },
        { ingrediente: "Verde brillante", cantidad: "0.025 g" },
        { ingrediente: "Agar", cantidad: "20 g" }
      ],
      preparacion: {
        temperatura: "Enfriar a 45-50 °C antes de servir",
        esterilizacion: "No autoclave",
        noAutoclave: true,
        pasos: [
          "Suspender el polvo en agua destilada.",
          "Calentar con agitación y hervir cerca de 1 minuto.",
          "No autoclave: la selectividad disminuye con calor excesivo.",
          "Servir 20 mL por placa en condiciones estériles.",
          "Preparar idealmente el día previo y proteger de la luz."
        ]
      },
      interpretacionVisual: "Colonias negras, marrón-negras o con brillo metálico sugieren Salmonella productora de H2S.",
      colorColonias: "Negras / brillo metálico sobre medio verde-pardo.",
      riesgosBiologicos: ["Patógeno entérico", "Potencial zoonótico", "Manipular en bioseguridad adecuada"],
      notasLab: "La selectividad cae después de 48 h; mantener placas en oscuridad.",
      relaciones: {
        bacterias: ["salmonella-spp"],
        caldos: ["selenite-cystine-broth", "tetrathionate-broth", "buffered-peptone-water"],
        pruebas: ["tsi", "sim", "citrato-simmons", "ureasa"],
        antibioticos: ["enrofloxacina", "ciprofloxacina", "trimetoprim-sulfa"]
      }
    },
    {
      id: "macconkey-agar",
      tipoEntidad: "agar",
      nombre: "MacConkey Agar",
      alternativo: "MAC",
      subtitulo: "Para: bacilos Gram negativos entéricos",
      tipos: ["selectivo", "diferencial", "enterobacterias"],
      gramosPorLitro: 51.5,
      phFinal: "7.1 ± 0.2",
      objetivo: "Aislar enterobacterias y diferenciar fermentadoras de lactosa.",
      bacteriasObjetivoIds: ["escherichia-coli", "salmonella-spp", "klebsiella-pneumoniae", "proteus-mirabilis"],
      bacteriasInhibidas: ["Gram positivas por sales biliares y cristal violeta"],
      composicion: [
        { ingrediente: "Peptona", cantidad: "17 g" },
        { ingrediente: "Lactosa", cantidad: "10 g" },
        { ingrediente: "Sales biliares", cantidad: "1.5 g" },
        { ingrediente: "NaCl", cantidad: "5 g" },
        { ingrediente: "Rojo neutro", cantidad: "0.03 g" },
        { ingrediente: "Cristal violeta", cantidad: "0.001 g" },
        { ingrediente: "Agar", cantidad: "13.5 g" }
      ],
      preparacion: {
        temperatura: "Servir a 45-50 °C",
        esterilizacion: "Autoclave 121 °C por 15 min",
        noAutoclave: false,
        pasos: [
          "Suspender el medio en agua destilada.",
          "Calentar hasta disolver completamente.",
          "Autoclavar a 121 °C por 15 minutos.",
          "Enfriar a 45-50 °C y servir en placas estériles."
        ]
      },
      interpretacionVisual: "Colonias rosadas: lactosa positivas. Colonias incoloras: no fermentadoras de lactosa.",
      colorColonias: "E. coli rosado intenso; Salmonella incolora; Klebsiella mucoide rosada.",
      riesgosBiologicos: ["Muestras fecales", "Enterobacterias zoonóticas posibles"],
      notasLab: "Útil como punto de entrada para pruebas TSI, SIM, citrato e indol.",
      relaciones: {
        bacterias: ["escherichia-coli", "salmonella-spp", "klebsiella-pneumoniae", "proteus-mirabilis"],
        caldos: ["buffered-peptone-water", "tryptic-soy-broth"],
        pruebas: ["tsi", "sim", "citrato-simmons", "indol"],
        antibioticos: ["enrofloxacina", "gentamicina", "trimetoprim-sulfa", "amoxicilina-clavulanato"]
      }
    },
    {
      id: "mueller-hinton-agar",
      tipoEntidad: "agar",
      nombre: "Mueller Hinton Agar",
      alternativo: "MHA / agar para antibiograma",
      subtitulo: "Para: sensibilidad antimicrobiana",
      tipos: ["antibiograma", "nutritivo", "clsi"],
      gramosPorLitro: 38,
      phFinal: "7.3 ± 0.2",
      objetivo: "Estándar para difusión en disco y lectura de halos de inhibición.",
      bacteriasObjetivoIds: ["escherichia-coli", "staphylococcus-spp", "pseudomonas-aeruginosa", "pasteurella-multocida", "klebsiella-pneumoniae"],
      bacteriasInhibidas: ["No selectivo: no inhibe de forma intencional"],
      composicion: [
        { ingrediente: "Infusión de carne", cantidad: "2 g" },
        { ingrediente: "Hidrolizado ácido de caseína", cantidad: "17.5 g" },
        { ingrediente: "Almidón", cantidad: "1.5 g" },
        { ingrediente: "Agar", cantidad: "17 g" }
      ],
      preparacion: {
        temperatura: "Servir a 45-50 °C",
        esterilizacion: "Autoclave 121 °C por 15 min",
        noAutoclave: false,
        pasos: [
          "Suspender 38 g por litro en agua desmineralizada o destilada.",
          "Calentar hasta disolver.",
          "Autoclavar a 121 °C por 15 minutos.",
          "Servir a espesor uniforme para antibiograma."
        ]
      },
      interpretacionVisual: "Césped bacteriano homogéneo con halos nítidos alrededor de discos.",
      colorColonias: "Medio ámbar claro; colonias según microorganismo.",
      riesgosBiologicos: ["Aerosoles al preparar inóculo", "Lectura dependiente de cepa y estándar"],
      notasLab: "Controlar pH, espesor y concentración del inóculo; pequeñas variaciones alteran halos.",
      relaciones: {
        bacterias: ["escherichia-coli", "staphylococcus-spp", "pseudomonas-aeruginosa", "pasteurella-multocida", "klebsiella-pneumoniae"],
        caldos: ["tryptic-soy-broth", "thioglycollate-broth"],
        pruebas: ["catalasa", "oxidasa"],
        antibioticos: ["enrofloxacina", "ciprofloxacina", "gentamicina", "ceftiofur", "oxitetraciclina", "amoxicilina-clavulanato"]
      }
    },
    {
      id: "mannitol-salt-agar",
      tipoEntidad: "agar",
      nombre: "Mannitol Salt Agar",
      alternativo: "MSA",
      subtitulo: "Para: Staphylococcus spp.",
      tipos: ["selectivo", "diferencial", "halotolerante"],
      gramosPorLitro: 111,
      phFinal: "7.4 ± 0.2",
      objetivo: "Seleccionar estafilococos por tolerancia a NaCl y diferenciar fermentación de manitol.",
      bacteriasObjetivoIds: ["staphylococcus-spp"],
      bacteriasInhibidas: ["Bacterias no halotolerantes", "muchos Gram negativos"],
      composicion: [
        { ingrediente: "Peptonas", cantidad: "10 g" },
        { ingrediente: "Extracto de carne", cantidad: "1 g" },
        { ingrediente: "NaCl", cantidad: "75 g" },
        { ingrediente: "D-manitol", cantidad: "10 g" },
        { ingrediente: "Rojo fenol", cantidad: "0.025 g" },
        { ingrediente: "Agar", cantidad: "15 g" }
      ],
      preparacion: {
        temperatura: "Servir a 45-50 °C",
        esterilizacion: "Autoclave 121 °C por 15 min",
        noAutoclave: false,
        pasos: [
          "Suspender el medio deshidratado.",
          "Calentar con agitación hasta disolver.",
          "Autoclavar a 121 °C por 15 minutos.",
          "Enfriar y servir placas."
        ]
      },
      interpretacionVisual: "Viraje amarillo alrededor de colonias: fermentación de manitol.",
      colorColonias: "Colonias cremosas; halo amarillo en fermentadoras.",
      riesgosBiologicos: ["Estafilococos oportunistas", "Riesgo de cepas resistentes"],
      notasLab: "Confirmar con catalasa, coagulasa y perfil clínico.",
      relaciones: {
        bacterias: ["staphylococcus-spp"],
        caldos: ["tryptic-soy-broth"],
        pruebas: ["catalasa", "coagulasa"],
        antibioticos: ["amoxicilina-clavulanato", "ceftiofur", "oxitetraciclina"]
      }
    },
    {
      id: "blood-agar",
      tipoEntidad: "agar",
      nombre: "Agar Sangre",
      alternativo: "BAP",
      subtitulo: "Para: bacterias exigentes y hemólisis",
      tipos: ["enriquecido", "diferencial", "hemolisis"],
      gramosPorLitro: 40,
      phFinal: "7.3 ± 0.2",
      objetivo: "Cultivar bacterias exigentes y observar patrones de hemólisis.",
      bacteriasObjetivoIds: ["staphylococcus-spp", "streptococcus-spp", "pasteurella-multocida"],
      bacteriasInhibidas: ["No selectivo; puede requerir condiciones especiales"],
      composicion: [
        { ingrediente: "Base nutritiva", cantidad: "40 g" },
        { ingrediente: "Sangre desfibrinada", cantidad: "5-10%" }
      ],
      preparacion: {
        temperatura: "Agregar sangre a 45-50 °C",
        esterilizacion: "Autoclave de la base; no autoclave con sangre",
        noAutoclave: false,
        pasos: [
          "Preparar y autoclavar la base.",
          "Enfriar a 45-50 °C.",
          "Agregar sangre desfibrinada estéril.",
          "Mezclar suavemente y servir placas."
        ]
      },
      interpretacionVisual: "Beta: halo claro; alfa: halo verdoso; gamma: sin hemólisis.",
      colorColonias: "Variable; observar hemólisis alrededor de la colonia.",
      riesgosBiologicos: ["Material biológico", "Patógenos respiratorios o cutáneos"],
      notasLab: "Evitar agregar sangre con el medio demasiado caliente para no lisar células.",
      relaciones: {
        bacterias: ["staphylococcus-spp", "streptococcus-spp", "pasteurella-multocida"],
        caldos: ["tryptic-soy-broth", "thioglycollate-broth"],
        pruebas: ["catalasa", "coagulasa", "oxidasa"],
        antibioticos: ["amoxicilina-clavulanato", "ceftiofur", "enrofloxacina"]
      }
    },
    {
      id: "xld-agar",
      tipoEntidad: "agar",
      nombre: "XLD Agar",
      alternativo: "Xylose Lysine Deoxycholate",
      subtitulo: "Para: Salmonella y Shigella",
      tipos: ["selectivo", "diferencial", "enteropatogenos"],
      gramosPorLitro: 55,
      phFinal: "7.4 ± 0.2",
      objetivo: "Diferenciar enteropatógenos por fermentación de xilosa, descarboxilación de lisina y H2S.",
      bacteriasObjetivoIds: ["salmonella-spp"],
      bacteriasInhibidas: ["Gram positivas", "flora intestinal sensible a desoxicolato"],
      composicion: [
        { ingrediente: "Extracto de levadura", cantidad: "3 g" },
        { ingrediente: "Xilosa / lactosa / sacarosa", cantidad: "22.5 g" },
        { ingrediente: "L-lisina", cantidad: "5 g" },
        { ingrediente: "Desoxicolato sódico", cantidad: "2.5 g" },
        { ingrediente: "Tiosulfato / citrato férrico", cantidad: "6.8 g" },
        { ingrediente: "Agar", cantidad: "13.5 g" }
      ],
      preparacion: {
        temperatura: "No sobrecalentar; servir a 45-50 °C",
        esterilizacion: "Hervir hasta disolver; no sobreautoclavar",
        noAutoclave: true,
        pasos: [
          "Suspender y calentar con agitación.",
          "Evitar calentamiento prolongado.",
          "Enfriar a 45-50 °C.",
          "Servir placas en condiciones estériles."
        ]
      },
      interpretacionVisual: "Salmonella: colonias rojas con centro negro. Fermentadoras: amarillas.",
      colorColonias: "Rojo con centro negro para H2S positivo.",
      riesgosBiologicos: ["Enteropatógenos zoonóticos", "Muestras fecales"],
      notasLab: "Usar junto a enriquecimiento selectivo y confirmación bioquímica.",
      relaciones: {
        bacterias: ["salmonella-spp", "escherichia-coli", "proteus-mirabilis"],
        caldos: ["selenite-cystine-broth", "tetrathionate-broth"],
        pruebas: ["tsi", "sim", "citrato-simmons"],
        antibioticos: ["enrofloxacina", "ciprofloxacina", "trimetoprim-sulfa"]
      }
    }
  ],

  caldos: [
    {
      id: "buffered-peptone-water",
      tipoEntidad: "caldo",
      nombre: "Buffered Peptone Water",
      alternativo: "BPW / Agua peptonada tamponada",
      subtitulo: "Para: preenriquecimiento de enterobacterias",
      tipos: ["preenriquecimiento", "nutritivo", "no selectivo"],
      gramosPorLitro: 20,
      phFinal: "7.2 ± 0.2",
      objetivo: "Recuperar bacterias lesionadas antes de enriquecimientos selectivos.",
      bacteriasObjetivoIds: ["salmonella-spp", "escherichia-coli"],
      composicion: [
        { ingrediente: "Peptona", cantidad: "10 g" },
        { ingrediente: "NaCl", cantidad: "5 g" },
        { ingrediente: "Fosfato disódico", cantidad: "3.5 g" },
        { ingrediente: "Fosfato monopotásico", cantidad: "1.5 g" }
      ],
      preparacion: {
        temperatura: "Disolver antes de esterilizar",
        esterilizacion: "Autoclave 121 °C por 15 min",
        noAutoclave: false,
        pasos: ["Suspender en agua destilada.", "Distribuir en frascos o tubos.", "Autoclavar.", "Enfriar antes de inocular."]
      },
      interpretacionVisual: "Turbidez sugiere crecimiento; no es diferencial.",
      notasLab: "Paso previo útil antes de caldos selectivos para Salmonella.",
      relaciones: {
        bacterias: ["salmonella-spp", "escherichia-coli"],
        agares: ["bismuth-sulfite-agar", "xld-agar", "macconkey-agar"],
        pruebas: ["tsi", "sim", "citrato-simmons"],
        antibioticos: ["enrofloxacina", "trimetoprim-sulfa"]
      }
    },
    {
      id: "selenite-cystine-broth",
      tipoEntidad: "caldo",
      nombre: "Caldo Selenito Cistina",
      alternativo: "SC Broth",
      subtitulo: "Para: enriquecimiento selectivo de Salmonella",
      tipos: ["selectivo", "enriquecimiento", "salmonella"],
      gramosPorLitro: 23,
      phFinal: "7.0 ± 0.2",
      objetivo: "Favorecer Salmonella e inhibir parte de la flora intestinal competidora.",
      bacteriasObjetivoIds: ["salmonella-spp"],
      composicion: [
        { ingrediente: "Peptona", cantidad: "5 g" },
        { ingrediente: "Lactosa", cantidad: "4 g" },
        { ingrediente: "Selenito sódico", cantidad: "4 g" },
        { ingrediente: "L-cistina", cantidad: "0.01 g" },
        { ingrediente: "Fosfatos", cantidad: "10 g" }
      ],
      preparacion: {
        temperatura: "Evitar sobrecalentamiento",
        esterilizacion: "No autoclave en formulaciones sensibles",
        noAutoclave: true,
        pasos: ["Disolver con calor suave.", "Evitar ebullición prolongada.", "Distribuir asépticamente.", "Incubar según protocolo."]
      },
      interpretacionVisual: "Turbidez variable; subcultivar a agar selectivo.",
      notasLab: "El selenito es tóxico; manipular polvo con cuidado.",
      relaciones: {
        bacterias: ["salmonella-spp"],
        agares: ["bismuth-sulfite-agar", "xld-agar"],
        pruebas: ["tsi", "sim", "citrato-simmons"],
        antibioticos: ["ciprofloxacina", "trimetoprim-sulfa"]
      }
    },
    {
      id: "tetrathionate-broth",
      tipoEntidad: "caldo",
      nombre: "Caldo Tetrationato",
      alternativo: "TT Broth",
      subtitulo: "Para: enriquecimiento de Salmonella",
      tipos: ["selectivo", "enriquecimiento", "salmonella"],
      gramosPorLitro: 46,
      phFinal: "8.0 ± 0.2",
      objetivo: "Enriquecimiento selectivo de Salmonella en muestras con flora mixta.",
      bacteriasObjetivoIds: ["salmonella-spp"],
      composicion: [
        { ingrediente: "Peptona", cantidad: "5 g" },
        { ingrediente: "Sales biliares", cantidad: "1 g" },
        { ingrediente: "Carbonato cálcico", cantidad: "10 g" },
        { ingrediente: "Tiosulfato sódico", cantidad: "30 g" },
        { ingrediente: "Yodo-yoduro", cantidad: "Suplemento" }
      ],
      preparacion: {
        temperatura: "Agregar yodo cuando corresponda, ya frío",
        esterilizacion: "No autoclave con suplementos termosensibles",
        noAutoclave: true,
        pasos: ["Preparar la base.", "Enfriar.", "Añadir suplemento yodo-yoduro de forma aséptica.", "Usar según protocolo."]
      },
      interpretacionVisual: "Subcultivar a agar selectivo; no usar color como diagnóstico final.",
      notasLab: "Muy útil cuando se sospecha Salmonella con flora acompañante abundante.",
      relaciones: {
        bacterias: ["salmonella-spp"],
        agares: ["bismuth-sulfite-agar", "xld-agar"],
        pruebas: ["tsi", "sim"],
        antibioticos: ["enrofloxacina", "ciprofloxacina"]
      }
    },
    {
      id: "tryptic-soy-broth",
      tipoEntidad: "caldo",
      nombre: "Tryptic Soy Broth",
      alternativo: "TSB",
      subtitulo: "Para: crecimiento general",
      tipos: ["nutritivo", "no selectivo", "uso general"],
      gramosPorLitro: 30,
      phFinal: "7.3 ± 0.2",
      objetivo: "Cultivo general, recuperación bacteriana y preparación de inóculos.",
      bacteriasObjetivoIds: ["escherichia-coli", "staphylococcus-spp", "pseudomonas-aeruginosa", "pasteurella-multocida"],
      composicion: [
        { ingrediente: "Digerido pancreático de caseína", cantidad: "17 g" },
        { ingrediente: "Digerido papaico de soya", cantidad: "3 g" },
        { ingrediente: "NaCl", cantidad: "5 g" },
        { ingrediente: "Fosfato dipotásico", cantidad: "2.5 g" },
        { ingrediente: "Glucosa", cantidad: "2.5 g" }
      ],
      preparacion: {
        temperatura: "Disolver completamente",
        esterilizacion: "Autoclave 121 °C por 15 min",
        noAutoclave: false,
        pasos: ["Suspender 30 g/L.", "Distribuir.", "Autoclavar.", "Enfriar y almacenar protegido."]
      },
      interpretacionVisual: "Turbidez indica crecimiento.",
      notasLab: "No selectivo; útil para reactivar cultivos antes de pruebas.",
      relaciones: {
        bacterias: ["escherichia-coli", "staphylococcus-spp", "pseudomonas-aeruginosa", "pasteurella-multocida"],
        agares: ["mueller-hinton-agar", "blood-agar", "mannitol-salt-agar", "macconkey-agar"],
        pruebas: ["catalasa", "oxidasa", "coagulasa"],
        antibioticos: ["enrofloxacina", "gentamicina", "ceftiofur"]
      }
    },
    {
      id: "thioglycollate-broth",
      tipoEntidad: "caldo",
      nombre: "Caldo Tioglicolato",
      alternativo: "Fluid Thioglycollate Medium",
      subtitulo: "Para: aerobios, anaerobios y microaerófilos",
      tipos: ["enriquecido", "redox", "anaerobios"],
      gramosPorLitro: 29.8,
      phFinal: "7.1 ± 0.2",
      objetivo: "Evaluar crecimiento según requerimiento de oxígeno y recuperar bacterias exigentes.",
      bacteriasObjetivoIds: ["streptococcus-spp", "pasteurella-multocida", "staphylococcus-spp"],
      composicion: [
        { ingrediente: "Peptonas", cantidad: "20 g" },
        { ingrediente: "Glucosa", cantidad: "5 g" },
        { ingrediente: "Tioglicolato sódico", cantidad: "0.5 g" },
        { ingrediente: "L-cistina", cantidad: "0.5 g" },
        { ingrediente: "Agar bajo", cantidad: "0.75 g" },
        { ingrediente: "Resazurina", cantidad: "Indicador" }
      ],
      preparacion: {
        temperatura: "Recalentar suavemente si hay oxidación superficial",
        esterilizacion: "Autoclave 121 °C por 15 min",
        noAutoclave: false,
        pasos: ["Suspender el medio.", "Calentar hasta disolver.", "Distribuir en tubos profundos.", "Autoclavar y enfriar sin agitar excesivamente."]
      },
      interpretacionVisual: "Crecimiento superficial: aerobio; crecimiento profundo: anaerobio o microaerófilo.",
      notasLab: "La banda rosada indica oxidación; no agitar antes de interpretar.",
      relaciones: {
        bacterias: ["streptococcus-spp", "pasteurella-multocida", "staphylococcus-spp"],
        agares: ["blood-agar", "mueller-hinton-agar"],
        pruebas: ["catalasa", "oxidasa"],
        antibioticos: ["amoxicilina-clavulanato", "ceftiofur", "enrofloxacina"]
      }
    }
  ],

  pruebas: [
    {
      id: "tsi",
      tipoEntidad: "prueba",
      nombre: "TSI",
      alternativo: "Triple Sugar Iron Agar",
      subtitulo: "Para: enterobacterias",
      tipos: ["fermentación", "h2s", "gas"],
      fundamento: "Evalúa fermentación de glucosa, lactosa/sacarosa, producción de gas y H2S.",
      principioBioquimico: "Cambios de pH por fermentación y precipitado negro por sulfuro de hierro.",
      reactivos: ["Rojo fenol", "Tiosulfato", "Sales de hierro"],
      interpretacionPositiva: "A/A o K/A con gas o H2S según patrón.",
      interpretacionNegativa: "K/K o sin fermentación significativa.",
      utilidadDiagnostica: "Separación rápida de enterobacterias fermentadoras y H2S positivas.",
      erroresComunes: ["Leer después de 24 h puede revertir la pendiente", "Inóculo excesivo altera lectura"],
      bacteriasIds: ["salmonella-spp", "escherichia-coli", "klebsiella-pneumoniae", "proteus-mirabilis"],
      mediosIds: ["macconkey-agar", "bismuth-sulfite-agar", "xld-agar"],
      pruebasComplementariasIds: ["sim", "citrato-simmons", "ureasa"]
    },
    {
      id: "sim",
      tipoEntidad: "prueba",
      nombre: "SIM",
      alternativo: "Sulfuro Indol Motilidad",
      subtitulo: "Para: enterobacterias móviles/H2S",
      tipos: ["motilidad", "indol", "h2s"],
      fundamento: "Evalúa producción de H2S, indol y motilidad bacteriana en medio semisólido.",
      principioBioquimico: "Tiosulfato y hierro detectan H2S; Kovacs detecta indol.",
      reactivos: ["Reactivo de Kovacs", "Sales de hierro", "Tiosulfato"],
      interpretacionPositiva: "Negro: H2S; anillo rojo: indol; difusión: motilidad.",
      interpretacionNegativa: "Sin negro, sin anillo rojo o crecimiento solo en línea de punción.",
      utilidadDiagnostica: "Complementa TSI en sospecha de Salmonella, E. coli y Proteus.",
      erroresComunes: ["Agitar el tubo", "Punción torcida", "Añadir Kovacs antes de leer motilidad"],
      bacteriasIds: ["salmonella-spp", "escherichia-coli", "proteus-mirabilis"],
      mediosIds: ["macconkey-agar", "xld-agar", "bismuth-sulfite-agar"],
      pruebasComplementariasIds: ["tsi", "citrato-simmons", "indol"]
    },
    {
      id: "citrato-simmons",
      tipoEntidad: "prueba",
      nombre: "Citrato Simmons",
      alternativo: "Simmons Citrate Agar",
      subtitulo: "Para: uso de citrato como carbono",
      tipos: ["citrato", "metabolismo"],
      fundamento: "Determina si la bacteria usa citrato como única fuente de carbono.",
      principioBioquimico: "Alcalinización del medio con azul de bromotimol.",
      reactivos: ["Azul de bromotimol", "Citrato sódico"],
      interpretacionPositiva: "Crecimiento con viraje azul.",
      interpretacionNegativa: "Verde sin crecimiento visible.",
      utilidadDiagnostica: "Diferencia Salmonella/Klebsiella de E. coli en esquemas clásicos.",
      erroresComunes: ["Inóculo cargado arrastra nutrientes", "Leer crecimiento sin cambio de color"],
      bacteriasIds: ["salmonella-spp", "klebsiella-pneumoniae", "escherichia-coli"],
      mediosIds: ["macconkey-agar", "bismuth-sulfite-agar"],
      pruebasComplementariasIds: ["tsi", "sim", "ureasa"]
    },
    {
      id: "ureasa",
      tipoEntidad: "prueba",
      nombre: "Ureasa",
      alternativo: "Urea Agar / Urea Broth",
      subtitulo: "Para: Proteus y ureasa positivos",
      tipos: ["enzimática", "urea"],
      fundamento: "Detecta hidrólisis de urea a amoníaco por ureasa.",
      principioBioquimico: "El amoníaco alcaliniza el medio y cambia el indicador a rosa intenso.",
      reactivos: ["Urea", "Rojo fenol"],
      interpretacionPositiva: "Rosa/fucsia intenso.",
      interpretacionNegativa: "Sin cambio o amarillo pálido.",
      utilidadDiagnostica: "Identifica Proteus y diferencia enterobacterias ureasa positivas.",
      erroresComunes: ["Incubar demasiado y leer falsos tardíos", "Medio vencido por degradación de urea"],
      bacteriasIds: ["proteus-mirabilis", "klebsiella-pneumoniae"],
      mediosIds: ["macconkey-agar"],
      pruebasComplementariasIds: ["tsi", "sim", "citrato-simmons"]
    },
    {
      id: "catalasa",
      tipoEntidad: "prueba",
      nombre: "Catalasa",
      alternativo: "Prueba con H2O2",
      subtitulo: "Para: cocos Gram positivos",
      tipos: ["enzimática", "rápida"],
      fundamento: "Detecta degradación de peróxido de hidrógeno por catalasa.",
      principioBioquimico: "Liberación de oxígeno visible como burbujeo.",
      reactivos: ["Peróxido de hidrógeno 3%"],
      interpretacionPositiva: "Burbujeo inmediato.",
      interpretacionNegativa: "Sin burbujeo.",
      utilidadDiagnostica: "Diferencia Staphylococcus (positivo) de Streptococcus (negativo).",
      erroresComunes: ["Tomar colonia de agar sangre y arrastrar eritrocitos", "Usar reactivo viejo"],
      bacteriasIds: ["staphylococcus-spp", "streptococcus-spp"],
      mediosIds: ["blood-agar", "mannitol-salt-agar"],
      pruebasComplementariasIds: ["coagulasa"]
    },
    {
      id: "coagulasa",
      tipoEntidad: "prueba",
      nombre: "Coagulasa",
      alternativo: "Coagulasa en porta/tubo",
      subtitulo: "Para: estafilococos patógenos",
      tipos: ["enzimática", "virulencia"],
      fundamento: "Detecta coagulasa libre o ligada asociada a patogenicidad estafilocócica.",
      principioBioquimico: "Conversión de fibrinógeno en fibrina visible como coágulo.",
      reactivos: ["Plasma citratado"],
      interpretacionPositiva: "Coágulo o aglutinación según método.",
      interpretacionNegativa: "Suspensión homogénea sin coagulación.",
      utilidadDiagnostica: "Apoya identificación de Staphylococcus aureus/pseudintermedius.",
      erroresComunes: ["Leer porta como definitivo cuando hay dudas", "Incubación excesiva con fibrinólisis"],
      bacteriasIds: ["staphylococcus-spp"],
      mediosIds: ["mannitol-salt-agar", "blood-agar"],
      pruebasComplementariasIds: ["catalasa"]
    },
    {
      id: "oxidasa",
      tipoEntidad: "prueba",
      nombre: "Oxidasa",
      alternativo: "Citocromo c oxidasa",
      subtitulo: "Para: Pseudomonas, Pasteurella y no fermentadores",
      tipos: ["enzimática", "respiratoria"],
      fundamento: "Detecta presencia de citocromo c oxidasa.",
      principioBioquimico: "El reactivo se oxida y vira a púrpura oscuro.",
      reactivos: ["Tetrametil-p-fenilendiamina"],
      interpretacionPositiva: "Púrpura en segundos.",
      interpretacionNegativa: "Sin viraje.",
      utilidadDiagnostica: "Diferencia no fermentadores oxidasa positivos de enterobacterias oxidasa negativas.",
      erroresComunes: ["Leer tarde produce falsos positivos", "Usar asas metálicas oxidadas"],
      bacteriasIds: ["pseudomonas-aeruginosa", "pasteurella-multocida", "escherichia-coli"],
      mediosIds: ["blood-agar", "mueller-hinton-agar"],
      pruebasComplementariasIds: ["catalasa", "tsi"]
    },
    {
      id: "indol",
      tipoEntidad: "prueba",
      nombre: "Indol",
      alternativo: "Kovacs / Ehrlich",
      subtitulo: "Para: producción de indol",
      tipos: ["enzimática", "triptofano"],
      fundamento: "Detecta degradación de triptófano a indol por triptofanasa.",
      principioBioquimico: "Kovacs reacciona con indol y forma anillo rojo.",
      reactivos: ["Reactivo de Kovacs"],
      interpretacionPositiva: "Anillo rojo cereza.",
      interpretacionNegativa: "Anillo amarillo o sin cambio.",
      utilidadDiagnostica: "Apoya diferenciación de E. coli frente a Klebsiella/Enterobacter.",
      erroresComunes: ["Medio sin triptófano", "Agregar reactivo antes de incubación adecuada"],
      bacteriasIds: ["escherichia-coli", "klebsiella-pneumoniae", "proteus-mirabilis"],
      mediosIds: ["macconkey-agar"],
      pruebasComplementariasIds: ["sim", "tsi", "citrato-simmons"]
    }
  ],

  antibioticos: [
    {
      id: "enrofloxacina",
      tipoEntidad: "antibiotico",
      nombre: "Enrofloxacina",
      subtitulo: "Para: bacilos Gram negativos y algunos Gram positivos",
      siglaDisco: "ENR5",
      familia: "Fluoroquinolona",
      familiaKey: "quinolona",
      tipoAccion: "Bactericida concentración-dependiente",
      mecanismo: "Inhibe ADN-girasa y topoisomerasa IV.",
      espectro: "Amplio; fuerte actividad frente a Gram negativos.",
      espectroKey: "amplio",
      bacteriasSensiblesIds: ["escherichia-coli", "pasteurella-multocida", "salmonella-spp"],
      bacteriasResistentesIds: ["staphylococcus-spp", "pseudomonas-aeruginosa"],
      usoClinico: "Infecciones respiratorias, urinarias y entéricas según cultivo y sensibilidad.",
      interpretacion: "Interpretar con criterios veterinarios vigentes cuando estén disponibles.",
      resistencia: "Mutaciones gyrA/parC, bombas de eflujo y uso repetido favorecen resistencia.",
      observaciones: "Evitar uso empírico prolongado; reservar cuando el antibiograma lo justifique.",
      pruebasRelacionadasIds: ["oxidasa", "tsi"],
      mediosIds: ["mueller-hinton-agar"]
    },
    {
      id: "ciprofloxacina",
      tipoEntidad: "antibiotico",
      nombre: "Ciprofloxacina",
      subtitulo: "Para: Enterobacteriaceae y no fermentadores",
      siglaDisco: "CIP5",
      familia: "Fluoroquinolona",
      familiaKey: "quinolona",
      tipoAccion: "Bactericida",
      mecanismo: "Bloqueo de replicación por inhibición de topoisomerasas.",
      espectro: "Gram negativos, Pseudomonas variable y algunos Gram positivos.",
      espectroKey: "amplio",
      bacteriasSensiblesIds: ["salmonella-spp", "escherichia-coli", "klebsiella-pneumoniae"],
      bacteriasResistentesIds: ["staphylococcus-spp"],
      usoClinico: "Referencia frecuente en antibiogramas; uso clínico veterinario depende de criterio local.",
      interpretacion: "Comparar halos con estándar aplicable al microorganismo y especie.",
      resistencia: "Resistencia cruzada dentro de quinolonas.",
      observaciones: "Útil para vigilancia de resistencia.",
      pruebasRelacionadasIds: ["tsi", "sim"],
      mediosIds: ["mueller-hinton-agar"]
    },
    {
      id: "amoxicilina-clavulanato",
      tipoEntidad: "antibiotico",
      nombre: "Amoxicilina / Ácido clavulánico",
      subtitulo: "Para: Gram positivos y beta-lactamasas sensibles",
      siglaDisco: "AMC30",
      familia: "Penicilina + inhibidor beta-lactamasa",
      familiaKey: "betalactamico",
      tipoAccion: "Bactericida tiempo-dependiente",
      mecanismo: "Inhibe síntesis de pared; clavulanato inhibe beta-lactamasas.",
      espectro: "Gram positivos, anaerobios y algunas enterobacterias.",
      espectroKey: "gram-positivo",
      bacteriasSensiblesIds: ["staphylococcus-spp", "streptococcus-spp", "pasteurella-multocida"],
      bacteriasResistentesIds: ["pseudomonas-aeruginosa", "klebsiella-pneumoniae"],
      usoClinico: "Piel, tejidos blandos, cavidad oral y respiratorio según sensibilidad.",
      interpretacion: "La producción de beta-lactamasas no siempre predice sensibilidad final.",
      resistencia: "Beta-lactamasas no inhibidas, cambios de PBPs, permeabilidad reducida.",
      observaciones: "No cubrir Pseudomonas.",
      pruebasRelacionadasIds: ["catalasa", "coagulasa"],
      mediosIds: ["mueller-hinton-agar", "blood-agar"]
    },
    {
      id: "gentamicina",
      tipoEntidad: "antibiotico",
      nombre: "Gentamicina",
      subtitulo: "Para: Gram negativos aerobios",
      siglaDisco: "CN10",
      familia: "Aminoglucósido",
      familiaKey: "aminoglucosido",
      tipoAccion: "Bactericida concentración-dependiente",
      mecanismo: "Unión irreversible a subunidad 30S con lectura errónea del ARNm.",
      espectro: "Gram negativos aerobios; sin actividad útil en anaerobios.",
      espectroKey: "gram-negativo",
      bacteriasSensiblesIds: ["escherichia-coli", "klebsiella-pneumoniae", "pseudomonas-aeruginosa"],
      bacteriasResistentesIds: ["streptococcus-spp"],
      usoClinico: "Infecciones graves por Gram negativos bajo monitoreo.",
      interpretacion: "Halos muy sensibles a cationes del medio y espesor del agar.",
      resistencia: "Enzimas modificadoras de aminoglucósidos, eflujo, menor entrada.",
      observaciones: "Nefrotoxicidad y ototoxicidad: vigilar función renal.",
      pruebasRelacionadasIds: ["oxidasa"],
      mediosIds: ["mueller-hinton-agar"]
    },
    {
      id: "ceftiofur",
      tipoEntidad: "antibiotico",
      nombre: "Ceftiofur",
      subtitulo: "Para: respiratorio y Gram negativos veterinarios",
      siglaDisco: "XNL30",
      familia: "Cefalosporina de tercera generación",
      familiaKey: "cefalosporina",
      tipoAccion: "Bactericida",
      mecanismo: "Inhibe síntesis de peptidoglicano de pared bacteriana.",
      espectro: "Gram negativos respiratorios y algunos Gram positivos.",
      espectroKey: "gram-negativo",
      bacteriasSensiblesIds: ["pasteurella-multocida", "escherichia-coli", "streptococcus-spp"],
      bacteriasResistentesIds: ["pseudomonas-aeruginosa"],
      usoClinico: "Respiratorio bovino/porcino y cuadros específicos según etiqueta y sensibilidad.",
      interpretacion: "No extrapolar halos a otras cefalosporinas sin criterio validado.",
      resistencia: "ESBL/AmpC y cambios de permeabilidad.",
      observaciones: "Antimicrobiano crítico; usar con diagnóstico.",
      pruebasRelacionadasIds: ["oxidasa", "catalasa"],
      mediosIds: ["mueller-hinton-agar"]
    },
    {
      id: "oxitetraciclina",
      tipoEntidad: "antibiotico",
      nombre: "Oxitetraciclina",
      subtitulo: "Para: amplio espectro y patógenos respiratorios",
      siglaDisco: "OT30",
      familia: "Tetraciclina",
      familiaKey: "tetraciclina",
      tipoAccion: "Bacteriostático",
      mecanismo: "Se une a 30S e inhibe unión de ARNt.",
      espectro: "Amplio: Gram positivos, Gram negativos, Mycoplasma y algunos intracelulares.",
      espectroKey: "amplio",
      bacteriasSensiblesIds: ["pasteurella-multocida", "streptococcus-spp"],
      bacteriasResistentesIds: ["escherichia-coli", "salmonella-spp", "pseudomonas-aeruginosa"],
      usoClinico: "Respiratorio, anaplasmosis y cuadros donde sensibilidad local sea favorable.",
      interpretacion: "Resistencia adquirida común en producción animal.",
      resistencia: "Bombas de eflujo tet y protección ribosomal.",
      observaciones: "No combinar de forma irreflexiva con bactericidas dependientes de crecimiento.",
      pruebasRelacionadasIds: ["tsi"],
      mediosIds: ["mueller-hinton-agar"]
    },
    {
      id: "trimetoprim-sulfa",
      tipoEntidad: "antibiotico",
      nombre: "Trimetoprim / Sulfonamida",
      subtitulo: "Para: enterobacterias sensibles y urinario",
      siglaDisco: "SXT25",
      familia: "Antifolatos",
      familiaKey: "sulfonamida",
      tipoAccion: "Bactericida por bloqueo secuencial",
      mecanismo: "Inhibe dos pasos de la síntesis de folato.",
      espectro: "Gram positivos y Gram negativos variables.",
      espectroKey: "amplio",
      bacteriasSensiblesIds: ["escherichia-coli", "salmonella-spp"],
      bacteriasResistentesIds: ["pseudomonas-aeruginosa"],
      usoClinico: "Urinario, piel y enterobacterias sensibles.",
      interpretacion: "Mueller Hinton debe controlar timidina/timina para evitar falsos resultados.",
      resistencia: "Genes dfr/sul, bypass metabólico y resistencia plasmídica.",
      observaciones: "Vigilar efectos adversos idiosincráticos.",
      pruebasRelacionadasIds: ["tsi", "indol"],
      mediosIds: ["mueller-hinton-agar"]
    }
  ],

  microorganismos: [
    {
      id: "escherichia-coli",
      tipoEntidad: "microorganismo",
      nombreCientifico: "Escherichia coli",
      subtitulo: "Enterobacteriaceae · bacilo Gram negativo",
      gramKey: "gramnegativo",
      gramTexto: "Gram negativo",
      morfologiaKey: "bacilo",
      familia: "Enterobacteriaceae",
      reservorio: "Microbiota intestinal de animales domésticos y humanos.",
      importancia: "Diarrea neonatal, colibacilosis, ITU, mastitis y septicemia.",
      patogenicidad: "Fimbrias, toxinas, adhesinas, cápsula y LPS según patotipo.",
      toxinas: ["Enterotoxinas LT/ST", "Shiga-toxina en patotipos específicos", "LPS"],
      sistemasClave: ["digestivo", "urinario", "mamario", "sistemico"],
      agaresIds: ["macconkey-agar", "mueller-hinton-agar"],
      caldosIds: ["buffered-peptone-water", "tryptic-soy-broth"],
      pruebasIds: ["tsi", "sim", "indol", "citrato-simmons"],
      antibioticosIds: ["enrofloxacina", "gentamicina", "trimetoprim-sulfa", "amoxicilina-clavulanato"],
      resistencia: ["ESBL", "AmpC", "quinolonas", "sulfonamidas"],
      zoonosis: "Algunos patotipos son zoonóticos y de importancia alimentaria.",
      observacionesClinicas: "Interpretar junto a muestra, carga bacteriana y signos clínicos.",
      notasLab: "Lactosa positiva en MacConkey; indol usualmente positivo."
    },
    {
      id: "salmonella-spp",
      tipoEntidad: "microorganismo",
      nombreCientifico: "Salmonella spp.",
      subtitulo: "Enterobacteriaceae · zoonosis entérica",
      gramKey: "gramnegativo",
      gramTexto: "Gram negativo",
      morfologiaKey: "bacilo",
      familia: "Enterobacteriaceae",
      reservorio: "Intestino de aves, reptiles, mamíferos y ambiente contaminado.",
      importancia: "Enteritis, septicemia, abortos y brotes alimentarios.",
      patogenicidad: "Invasión intestinal, supervivencia intracelular y endotoxemia.",
      toxinas: ["Endotoxina LPS", "Factores de invasión SPI"],
      sistemasClave: ["digestivo", "sistemico", "reproductivo"],
      agaresIds: ["bismuth-sulfite-agar", "xld-agar", "macconkey-agar", "mueller-hinton-agar"],
      caldosIds: ["buffered-peptone-water", "selenite-cystine-broth", "tetrathionate-broth"],
      pruebasIds: ["tsi", "sim", "citrato-simmons", "ureasa"],
      antibioticosIds: ["enrofloxacina", "ciprofloxacina", "trimetoprim-sulfa", "ceftiofur"],
      resistencia: ["Quinolonas", "cefalosporinas de importancia crítica", "multirresistencia plasmídica"],
      zoonosis: "Alta relevancia zoonótica y de salud pública.",
      observacionesClinicas: "Confirmar aislamiento con batería bioquímica y serotipificación si aplica.",
      notasLab: "H2S frecuente; en Bismuth Sulphite puede formar colonias negras metálicas."
    },
    {
      id: "staphylococcus-spp",
      tipoEntidad: "microorganismo",
      nombreCientifico: "Staphylococcus spp.",
      subtitulo: "Cocos Gram positivos · piel y mucosas",
      gramKey: "grampositivo",
      gramTexto: "Gram positivo",
      morfologiaKey: "coco",
      familia: "Staphylococcaceae",
      reservorio: "Piel, mucosas y oído externo de perros, gatos y animales de producción.",
      importancia: "Piodermia, otitis, mastitis, heridas y bacteriemias.",
      patogenicidad: "Adhesinas, biopelícula, enzimas, toxinas y evasión inmune.",
      toxinas: ["Hemolisinas", "Leucotoxinas", "Enterotoxinas en algunas cepas"],
      sistemasClave: ["dermatologico", "mamario", "sistemico", "urinario"],
      agaresIds: ["mannitol-salt-agar", "blood-agar", "mueller-hinton-agar"],
      caldosIds: ["tryptic-soy-broth", "thioglycollate-broth"],
      pruebasIds: ["catalasa", "coagulasa"],
      antibioticosIds: ["amoxicilina-clavulanato", "ceftiofur", "oxitetraciclina"],
      resistencia: ["Meticilina/mecA", "macrólidos", "tetraciclinas"],
      zoonosis: "Algunas especies y clones pueden transferirse entre animales y humanos.",
      observacionesClinicas: "El antibiograma es clave en piodermias recurrentes.",
      notasLab: "Catalasa positivo; coagulasa orienta especies patógenas."
    },
    {
      id: "pasteurella-multocida",
      tipoEntidad: "microorganismo",
      nombreCientifico: "Pasteurella multocida",
      subtitulo: "Pasteurellaceae · respiratorio",
      gramKey: "gramnegativo",
      gramTexto: "Gram negativo",
      morfologiaKey: "cocobacilo",
      familia: "Pasteurellaceae",
      reservorio: "Nasofaringe de aves, conejos, rumiantes, perros y gatos.",
      importancia: "Neumonía, septicemia, coriza, abscesos y mordeduras.",
      patogenicidad: "Cápsula, LPS, adhesinas y toxina dermonecrótica en cepas específicas.",
      toxinas: ["LPS", "Toxina dermonecrótica en cepas tipo D"],
      sistemasClave: ["respiratorio", "sistemico", "dermatologico"],
      agaresIds: ["blood-agar", "mueller-hinton-agar"],
      caldosIds: ["tryptic-soy-broth", "thioglycollate-broth"],
      pruebasIds: ["oxidasa", "catalasa"],
      antibioticosIds: ["ceftiofur", "amoxicilina-clavulanato", "enrofloxacina", "oxitetraciclina"],
      resistencia: ["Tetraciclinas variables", "beta-lactamasas ocasionales"],
      zoonosis: "Importante en heridas por mordedura y contacto estrecho.",
      observacionesClinicas: "Muestra respiratoria debe tomarse antes de antibióticos.",
      notasLab: "Oxidasa positiva; crecimiento en agar sangre."
    },
    {
      id: "pseudomonas-aeruginosa",
      tipoEntidad: "microorganismo",
      nombreCientifico: "Pseudomonas aeruginosa",
      subtitulo: "No fermentador · oportunista ambiental",
      gramKey: "gramnegativo",
      gramTexto: "Gram negativo",
      morfologiaKey: "bacilo",
      familia: "Pseudomonadaceae",
      reservorio: "Agua, suelos húmedos, ambientes hospitalarios y biofilms.",
      importancia: "Otitis crónica, heridas, neumonía, infecciones urinarias y sepsis oportunista.",
      patogenicidad: "Biofilm, exotoxina A, elastasas, pigmentos y resistencia intrínseca.",
      toxinas: ["Exotoxina A", "Piocianina", "Elastasas"],
      sistemasClave: ["dermatologico", "respiratorio", "urinario", "sistemico"],
      agaresIds: ["mueller-hinton-agar", "blood-agar"],
      caldosIds: ["tryptic-soy-broth"],
      pruebasIds: ["oxidasa", "catalasa"],
      antibioticosIds: ["gentamicina", "ciprofloxacina", "enrofloxacina"],
      resistencia: ["Bombas de eflujo", "AmpC", "biofilm", "carbapenemasas"],
      zoonosis: "Oportunista; riesgo en pacientes inmunocomprometidos.",
      observacionesClinicas: "Requiere antibiograma; resistencia impredecible.",
      notasLab: "Oxidasa positiva; olor característico y pigmentos verdes/azules en algunos cultivos."
    },
    {
      id: "klebsiella-pneumoniae",
      tipoEntidad: "microorganismo",
      nombreCientifico: "Klebsiella pneumoniae",
      subtitulo: "Enterobacteriaceae · cápsula marcada",
      gramKey: "gramnegativo",
      gramTexto: "Gram negativo",
      morfologiaKey: "bacilo",
      familia: "Enterobacteriaceae",
      reservorio: "Intestino, mucosas, ambiente y superficies hospitalarias.",
      importancia: "Neumonía, mastitis, ITU y sepsis oportunista.",
      patogenicidad: "Cápsula antífagocítica, sideróforos, LPS y biopelícula.",
      toxinas: ["LPS"],
      sistemasClave: ["respiratorio", "urinario", "mamario", "sistemico"],
      agaresIds: ["macconkey-agar", "mueller-hinton-agar"],
      caldosIds: ["tryptic-soy-broth"],
      pruebasIds: ["citrato-simmons", "ureasa", "indol", "tsi"],
      antibioticosIds: ["gentamicina", "ceftiofur", "ciprofloxacina"],
      resistencia: ["ESBL", "carbapenemasas", "AmpC"],
      zoonosis: "Riesgo oportunista y nosocomial.",
      observacionesClinicas: "Colonias mucoides sugieren cápsula abundante.",
      notasLab: "Lactosa positiva mucoide en MacConkey; indol usualmente negativo."
    },
    {
      id: "proteus-mirabilis",
      tipoEntidad: "microorganismo",
      nombreCientifico: "Proteus mirabilis",
      subtitulo: "Enterobacteriaceae · ureasa positivo",
      gramKey: "gramnegativo",
      gramTexto: "Gram negativo",
      morfologiaKey: "bacilo",
      familia: "Enterobacteriaceae",
      reservorio: "Intestino, suelo y ambiente contaminado.",
      importancia: "ITU, urolitiasis por estruvita, heridas y otitis.",
      patogenicidad: "Ureasa, motilidad swarming, adhesinas y endotoxina.",
      toxinas: ["LPS", "Hemolisinas"],
      sistemasClave: ["urinario", "dermatologico"],
      agaresIds: ["macconkey-agar", "xld-agar", "mueller-hinton-agar"],
      caldosIds: ["tryptic-soy-broth"],
      pruebasIds: ["ureasa", "sim", "tsi", "indol"],
      antibioticosIds: ["gentamicina", "trimetoprim-sulfa", "amoxicilina-clavulanato"],
      resistencia: ["Tetraciclinas frecuentes", "resistencias plasmídicas variables"],
      zoonosis: "Oportunista; importancia clínica por ITU.",
      observacionesClinicas: "La alcalinización urinaria puede favorecer cálculos.",
      notasLab: "Ureasa rápida; swarming en medios no inhibitorios."
    },
    {
      id: "streptococcus-spp",
      tipoEntidad: "microorganismo",
      nombreCientifico: "Streptococcus spp.",
      subtitulo: "Cocos Gram positivos · cadenas",
      gramKey: "grampositivo",
      gramTexto: "Gram positivo",
      morfologiaKey: "coco",
      familia: "Streptococcaceae",
      reservorio: "Mucosas respiratorias, piel, tracto reproductivo y glándula mamaria.",
      importancia: "Mastitis, neumonía, septicemia neonatal, abscesos y endometritis.",
      patogenicidad: "Cápsula, hemolisinas, enzimas tisulares y evasión inmune.",
      toxinas: ["Estreptolisinas", "Exoenzimas"],
      sistemasClave: ["mamario", "respiratorio", "reproductivo", "sistemico"],
      agaresIds: ["blood-agar", "mueller-hinton-agar"],
      caldosIds: ["thioglycollate-broth"],
      pruebasIds: ["catalasa"],
      antibioticosIds: ["amoxicilina-clavulanato", "ceftiofur", "oxitetraciclina"],
      resistencia: ["Macrólidos", "tetraciclinas"],
      zoonosis: "Algunas especies tienen importancia zoonótica.",
      observacionesClinicas: "Interpretar hemólisis junto con especie animal y sitio anatómico.",
      notasLab: "Catalasa negativo; alfa/beta/gamma hemólisis en agar sangre."
    }
  ]
};
