// =============================================================================
// SUITE VET 2.0 — modules/micro/data.js
// SOLO DATOS. Importa los datos de antibio.js, micro.js y microorganismo.js
// originales y los expone como window.MICRO_DATA
// =============================================================================

window.MICRO_DATA = {

  agares: [
    { id: "tsa-agar", nombre: "Tryptic Soy Agar (TSA)", estado: "solido", tipos: ["basico","uso general"], gramosPorLitro: 40.0, phFinal: "7.3 ± 0.2", objetivo: "Medio nutritivo general para cultivo de bacterias no exigentes y control de esterilidad.", bacteriasObjetivo: ["Escherichia coli", "Flora ambiental no exigente"], observaciones: "Excelente crecimiento de bacterias no exigentes. Útil como base para conteos totales." },
    { id: "mannitol-salt-agar", nombre: "Mannitol Salt Agar", estado: "solido", tipos: ["selectivo","diferencial"], gramosPorLitro: 111.0, phFinal: "7.4 ± 0.2", objetivo: "Aislamiento y diferenciación de estafilococos por fermentación de manitol y tolerancia a alta sal.", bacteriasObjetivo: ["Staphylococcus spp."], observaciones: "Alta concentración de NaCl inhibe flora acompañante. Viraje a amarillo indica fermentación de manitol." },
    { id: "mueller-hinton-agar", nombre: "Mueller Hinton Agar", estado: "solido", tipos: ["basico","antibiograma"], gramosPorLitro: 38.0, phFinal: "7.3 ± 0.1", objetivo: "Medio estándar para pruebas de sensibilidad a antimicrobianos por difusión en disco.", bacteriasObjetivo: ["Escherichia coli", "Staphylococcus spp.", "Salmonella spp."], observaciones: "Controlar espesor de la capa (~4 mm) y pH para evitar halos falsamente aumentados o disminuidos." },
    { id: "macconkey-agar", nombre: "MacConkey Agar", estado: "solido", tipos: ["selectivo","diferencial"], gramosPorLitro: 51.5, phFinal: "7.1 ± 0.2", objetivo: "Aislamiento de enterobacterias y diferenciación por fermentación de lactosa.", bacteriasObjetivo: ["Escherichia coli", "Salmonella spp.", "Klebsiella spp."], observaciones: "Colonias rosadas = fermentadoras de lactosa. Incoloras = no fermentadoras." },
    { id: "blood-agar", nombre: "Agar Sangre (BAP)", estado: "solido", tipos: ["enriquecido","diferencial"], gramosPorLitro: 40.0, phFinal: "7.3 ± 0.2", objetivo: "Cultivo de bacterias exigentes y detección de hemólisis (alfa, beta, gamma).", bacteriasObjetivo: ["Streptococcus spp.", "Pasteurella spp.", "Arcanobacterium spp."], observaciones: "Hemólisis beta: zona clara completa. Alfa: verdosa. Gamma: sin cambio." }
  ],

  caldos: [
    { id: "tsb-caldo", nombre: "Tryptic Soy Broth (TSB)", estado: "liquido", tipos: ["nutritivo","no selectivo"], gramosPorLitro: 30.0, phFinal: "7.3 ± 0.2", objetivo: "Medio líquido universal para cultivo de bacterias y pruebas de esterilidad.", bacteriasObjetivo: ["Bacterias aerobias no exigentes"], observaciones: "Disolver 30 g/L en agua destilada y esterilizar a 121 °C durante 15 min." },
    { id: "agua-peptona", nombre: "Peptone Water", estado: "liquido", tipos: ["basico","preenriquecimiento"], gramosPorLitro: 15.0, phFinal: "7.2 ± 0.2", objetivo: "Medio simple para cultivo general y base para pruebas de fermentación.", bacteriasObjetivo: ["Enterobacterias", "Bacterias no exigentes"], observaciones: "Reconstituir 15 g/L en agua y esterilizar a 121 °C durante 15 min." }
  ],

  pruebas: [
    { id: "tsi", nombre: "TSI (Triple Sugar Iron)", categoria: "fermentacion", medioBase: "Triple Sugar Iron Agar", objetivo: "Diferenciar enterobacterias según fermentación de glucosa, lactosa, sacarosa y producción de gas/H₂S.", tipoInoculo: "Picadura en fondo + estría en la pendiente.", incubacion: "18–24 h a 35–37 °C.", interpretacion: "Fondo/pendiente amarillos → múltiples azúcares. Solo fondo amarillo → glucosa. Negro → H₂S. Elevación/rotura del agar → gas.", observaciones: "Leer dentro de las 24 h." },
    { id: "citrato-simmons", nombre: "Citrato de Simmons", categoria: "citrato", medioBase: "Simmons Citrate Agar", objetivo: "Evaluar la capacidad de utilizar citrato como única fuente de carbono.", tipoInoculo: "Estría superficial con asa recta.", incubacion: "24–48 h a 35–37 °C.", interpretacion: "Crecimiento con color azul → positivo. Verde sin crecimiento → negativo.", observaciones: "Evitar inóculos muy cargados que arrastren otros nutrientes." },
    { id: "ureasa", nombre: "Prueba de Ureasa", categoria: "lisina", medioBase: "Urea Agar / Urea Broth", objetivo: "Detectar producción de ureasa y liberación de amoníaco a partir de urea.", tipoInoculo: "Estría en superficie (agar) o inóculo directo (caldo).", incubacion: "4–24 h a 35–37 °C.", interpretacion: "Viraje a rosa intenso → positivo. Sin cambio (amarillo/pálido) → negativo.", observaciones: "Proteus spp. suelen ser fuertemente ureasa positivos con viraje rápido." }
  ],

  antibioticos: [
    { id: "enrofloxacina", nombre: "Enrofloxacina", siglaDisco: "ENR5", familia: "Fluoroquinolona", familiaKey: "quinolona", mecanismo: "Inhibe la ADN-girasa y la topoisomerasa IV, bloqueando la replicación del ADN.", tipoAccion: "Bactericida", espectro: "Amplio espectro, con énfasis en bacilos Gram negativos y algunos Gram positivos.", espectroKey: "amplio", microorganismosEjemplo: ["Escherichia coli", "Salmonella spp."], notasLab: "Evaluar con guías CLSI/BRCAST. Evitar uso como monoterapia prolongada." },
    { id: "amoxicilina-clavulanato", nombre: "Amoxicilina / Ácido clavulánico", siglaDisco: "AMC30", familia: "Penicilina + inhibidor β-lactamasa", familiaKey: "betalactamico", mecanismo: "Inhibe la síntesis de pared (amoxicilina) y bloquea β-lactamasas (clavulanato).", tipoAccion: "Bactericida", espectro: "Principalmente Gram positivos y algunas enterobacterias productoras de β-lactamasa.", espectroKey: "gram-positivo", microorganismosEjemplo: ["Staphylococcus intermedius", "Escherichia coli"], notasLab: "Controlar halos en cepas productoras de β-lactamasa." },
    { id: "gentamicina", nombre: "Gentamicina", siglaDisco: "CN10", familia: "Aminoglucósido", familiaKey: "aminoglucosido", mecanismo: "Se une de forma irreversible al ribosoma 30S, provocando lectura errónea del ARN mensajero.", tipoAccion: "Bactericida (dependiente de concentración)", espectro: "Bacilos Gram negativos aerobios, algunos cocos Gram positivos en combinación.", espectroKey: "gram-negativo", microorganismosEjemplo: ["Pseudomonas aeruginosa", "Escherichia coli"], notasLab: "Monitorear función renal en tratamientos prolongados. Nefrotóxico y ototóxico." },
    { id: "oxitetraciclina-disco", nombre: "Oxitetraciclina", siglaDisco: "OT30", familia: "Tetraciclina", familiaKey: "tetraciclina", mecanismo: "Se une al ribosoma 30S, inhibiendo la unión del ARNt al ARNm.", tipoAccion: "Bacteriostático", espectro: "Amplio espectro: Gram positivos, Gram negativos, Rickettsia, Mycoplasma.", espectroKey: "amplio", microorganismosEjemplo: ["Brucella spp.", "Mycoplasma spp."], notasLab: "Alta resistencia adquirida en enterobacterias de producción animal. Verificar sensibilidad local." },
    { id: "ceftiofur-disco", nombre: "Ceftiofur", siglaDisco: "XNL30", familia: "Cefalosporina 3ª gen.", familiaKey: "cefalosporina", mecanismo: "Inhibe la síntesis de peptidoglicano de la pared celular bacteriana.", tipoAccion: "Bactericida", espectro: "Principalmente Gram negativos y algunos Gram positivos; resistente a ciertas β-lactamasas.", espectroKey: "gram-negativo", microorganismosEjemplo: ["Pasteurella multocida", "Mannheimia haemolytica"], notasLab: "Leer halo con ceftiofur. NO extrapolar interpretación a otras cefalosporinas." }
  ],

  microorganismos: [
    { id: "escherichia-coli", nombreCientifico: "Escherichia coli", gramKey: "gramnegativo", gramTexto: "Gram negativo", morfologiaKey: "bacilo", familia: "Enterobacteriaceae", sistemasClave: ["digestivo","urinario","sistemico"], reservorio: "Microbiota intestinal normal de muchas especies domésticas.", importancia: "Oportunista frecuente. Causa diarreas neonatales, infecciones urinarias, mastitis y septicemias.", mecanismoPatogenicidad: "Adhesión mediante fimbrias, producción de toxinas (enterotoxinas, shiga-toxina) e invasión de mucosa según el patotipo.", notasLab: "En agar MacConkey produce colonias rosadas (fermenta lactosa). En TSI suele ser ácido/ácido con gas, sin H₂S." },
    { id: "salmonella-spp", nombreCientifico: "Salmonella spp.", gramKey: "gramnegativo", gramTexto: "Gram negativo", morfologiaKey: "bacilo", familia: "Enterobacteriaceae", sistemasClave: ["digestivo","sistemico"], reservorio: "Intestino de aves, reptiles y mamíferos; alimentos de origen animal.", importancia: "Causa gastroenteritis, septicemias y abortos; relevante en salud pública.", mecanismoPatogenicidad: "Invasión de enterocitos y placas de Peyer; supervivencia intracelular en macrófagos.", notasLab: "Colonias negras en medios con indicadores de H₂S (TSI, XLD, SS). Confirmar con pruebas bioquímicas." },
    { id: "staphylococcus-spp", nombreCientifico: "Staphylococcus spp.", gramKey: "grampositivo", gramTexto: "Gram positivo", morfologiaKey: "coco", familia: "Staphylococcaceae", sistemasClave: ["dermatologico","sistemico","urinario"], reservorio: "Piel y mucosas de mamíferos; portador normal en perros y gatos.", importancia: "Principal agente de piodermias, otitis, mastitis y bacteriemias.", mecanismoPatogenicidad: "Producción de toxinas (hemolisinas, coagulasa, leucotoxinas) y formación de biopelícula.", notasLab: "Catalasa positivo. Distinguir S. aureus (coagulasa +, colonias doradas) de estafilococos coagulasa negativos." },
    { id: "pasteurella-multocida", nombreCientifico: "Pasteurella multocida", gramKey: "gramnegativo", gramTexto: "Gram negativo", morfologiaKey: "bacilo", familia: "Pasteurellaceae", sistemasClave: ["respiratorio","sistemico"], reservorio: "Flora normal de nasofaringe de aves, conejos y muchas otras especies.", importancia: "Causa neumonías, septicemias hemorrágicas (bovinos, aves) y coriza.", mecanismoPatogenicidad: "Cápsula antifagocítica, lipopolisacárido y toxinas dermonecróticas en cepas tipo D.", notasLab: "Crecimiento en agar sangre (beta-hemólisis variable). Coloración bipolar característica en Gram." }
  ]
};
