// =============================================================================
// SUITE VET 2.0 — modules/fisio/data.js
// SOLO DATOS. Agrega aquí tus hormonas, vitaminas y glosario local.
// =============================================================================

window.FISIO_DATA = {

  hormonas: [
    { id: "progesterona", nombre: "Progesterona", sigla: "P4", sistema: "Reproductivo", sistemaKey: "reproductivo", origenLiberacion: "Cuerpo lúteo, placenta, glándula adrenal.", funcionPrincipal: "Mantenimiento de la gestación, preparación del útero para implantación.", funcionSecundaria: "Supresión del celo, desarrollo mamario, retroalimentación negativa sobre LH/FSH.", patologia: "Deficiencia → muerte embrionaria, aborto. Exceso → quistes luteales, anestro prolongado.", especieVariacion: "Vacas: cuerpo lúteo cíclico. Yeguas: mayor dependencia placentaria a partir del día 150.", afeccionesFarmaco: "Usada en sincronización de celos (CIDR, dispositivos intravaginales) y tratamiento de quistes." },
    { id: "estrogeno", nombre: "Estrógeno", sigla: "E2", sistema: "Reproductivo", sistemaKey: "reproductivo", origenLiberacion: "Folículo ovárico (granulosa), placenta, glándulas adrenales.", funcionPrincipal: "Inducción del celo, desarrollo de caracteres sexuales secundarios femeninos.", funcionSecundaria: "Preparación del tracto genital para la fecundación, retroalimentación positiva sobre LH (ovulación).", patologia: "Exceso → quistes foliculares, ninfomanía. Deficiencia → anestro, falla ovulatoria.", especieVariacion: "En cerdas y yeguas el E2 es el principal disparador del celo. En bovinos actúa en sinergia con la LH.", afeccionesFarmaco: "Benzoato de estradiol (BE) usado para sincronización de ovulación en protocolos IATF." },
    { id: "lh", nombre: "Hormona Luteinizante", sigla: "LH", sistema: "Reproductivo", sistemaKey: "reproductivo", origenLiberacion: "Adenohipófisis (gonadotropas), bajo control de GnRH.", funcionPrincipal: "Dispara la ovulación (pico preovulatorio). Forma el cuerpo lúteo.", funcionSecundaria: "Estimula síntesis de testosterona en células de Leydig (macho). Luteinización del folículo.", patologia: "Déficit → falla ovulatoria, anovulación. Exceso crónico → quistes luteínizados.", especieVariacion: "En bovinos el pico de LH es muy corto (~6 h). En yeguas el pico dura más y la ovulación es más lenta.", afeccionesFarmaco: "GnRH (análogos: buserelina, lecireína) → pico de LH inducido. Usada en protocolos IATF." },
    { id: "insulina", nombre: "Insulina", sigla: "INS", sistema: "Metabólico", sistemaKey: "metabolico", origenLiberacion: "Células β del páncreas (islotes de Langerhans).", funcionPrincipal: "Reduce la glucemia favoreciendo captación celular de glucosa, síntesis de glucógeno y lipogénesis.", funcionSecundaria: "Anabolismo proteico, inhibición de lipólisis y gluconeogénesis.", patologia: "Déficit → diabetes mellitus (hiperglucemia, poliuria, polidipsia). Exceso → hipoglucemia.", especieVariacion: "Gatos: muy susceptibles a diabetes tipo 2. Bovinos en lactación: resistencia insulínica periparturiente normal.", afeccionesFarmaco: "Insulina bovina/porcina usada en diabetes canina/felina. Insulinas de acción lenta (glargina) para gatos." },
    { id: "cortisol", nombre: "Cortisol", sigla: "CORT", sistema: "Metabólico", sistemaKey: "metabolico", origenLiberacion: "Corteza adrenal (zona fasciculada), bajo control de ACTH.", funcionPrincipal: "Respuesta al estrés, movilización de glucosa (gluconeogénesis), antiinflamatorio.", funcionSecundaria: "Inmunomodulación, mantenimiento de presión arterial, catabolismo proteico.", patologia: "Hipercortisolismo (Cushing) → polidipsia, poliuria, alopecia, pot de barro. Hipocortisolismo (Addison) → letargia, hipoglucemia.", especieVariacion: "Perros muy susceptibles a Cushing (PDH o tumor adrenal). Bovinos: cortisol el principal disparador del parto.", afeccionesFarmaco: "Dexametasona (análogo sintético) usada como antiinflamatorio. Prueba de supresión con dexametasona para Cushing." }
  ],

  vitaminas: [
    { id: "vit-a", nombre: "Vitamina A", sigla: "Vit A", tipo: "Liposoluble", otrosNombres: "Retinol, beta-caroteno (precursor)", funcion: "Visión (rodopsina), integridad epitelial y mucosas, reproducción, crecimiento óseo e inmunidad.", hipovitaminosis: "Ceguera nocturna, xeroftalmia, queratinización de mucosas, diarreas, abortos, crías débiles.", hipervitaminosis: "Lesiones óseas, exostosis, anorexia, pérdida de peso. Más frecuente en gatos con dietas a base de hígado.", variacionEspecies: "Bovinos convierten beta-caroteno en Vit A (forrajes). Gatos: incapaces de convertir beta-caroteno, requieren retinol directo.", afeccionesFarmaco: "Suplementación IM en bovinos preparto y en cerdas lactantes." },
    { id: "vit-d", nombre: "Vitamina D", sigla: "Vit D", tipo: "Liposoluble", otrosNombres: "Colecalciferol (D3), ergocalciferol (D2)", funcion: "Regulación del metabolismo del calcio y fósforo. Absorción intestinal de Ca²⁺. Calcificación ósea.", hipovitaminosis: "Raquitismo (animales jóvenes), osteomalacia (adultos), fiebre de leche (hipocalcemia posparto en vacas).", hipervitaminosis: "Hipercalcemia, calcificación de tejidos blandos (riñón, corazón, vasos), nefrocalcinosis.", variacionEspecies: "Rumiantes obtienen Vit D por exposición solar (UV). Aves dependen fuertemente de dieta.", afeccionesFarmaco: "Vitamina D3 IM en bovinos preparto para prevenir hipocalcemia. Calcitriol (forma activa) en insuficiencia renal crónica felina." },
    { id: "vit-e", nombre: "Vitamina E", sigla: "Vit E", tipo: "Liposoluble", otrosNombres: "Tocoferol (alfa-tocoferol es el más activo)", funcion: "Antioxidante liposoluble. Protege membranas celulares de la oxidación lipídica. Función inmune y reproductiva.", hipovitaminosis: "Enfermedad del músculo blanco (distrofia muscular nutricional). Terneros, corderos y potrillos. Junto con selenio.", hipervitaminosis: "Muy rara en animales. Puede interferir con absorción de otras vitaminas liposolubles a dosis extremas.", variacionEspecies: "Bovinos y ovinos muy sensibles en zonas con suelos pobres en selenio. Perros y gatos raramente deficientes.", afeccionesFarmaco: "Vitamina E + selenio (Bo-Se, Mu-Se) en prevencion de miopatía nutricional en bovinos y ovinos." },
    { id: "vit-b12", nombre: "Vitamina B12", sigla: "B12", tipo: "Hidrosoluble", otrosNombres: "Cobalamina, cianocobalamina", funcion: "Síntesis de ADN, metabolismo de ácidos grasos y aminoácidos, maduración eritrocitaria.", hipovitaminosis: "Anemia megaloblástica, pérdida de peso, debilidad, neuropatía. Corderos y bovinos en suelos pobres en cobalto.", hipervitaminosis: "No descrita en animales. Muy segura incluso a dosis altas.", variacionEspecies: "Rumiantes: sintetizada por microbiota ruminal si hay cobalto en la dieta. Perros y gatos requieren fuente dietética.", afeccionesFarmaco: "Inyección IM en síndromes de mala absorción y en deficiencia de cobalto en rumiantes." }
  ],

  // Glosario: si tienes servidor local (localhost:3000), déjalo vacío y se carga desde API.
  // Si quieres datos locales, agrégalos aquí con el mismo formato:
  // { termino, definicion, sistema }
  glosario: []
};
